flask:
  debug: true
  host: "127.0.0.1"
  port: 5000

logging:
  version: 1
  disable_existing_loggers: false
  formatters:
    simple:
      format: "[%(asctime)s] %(levelname)s in %(module)s: %(message)s"
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
  root:
    level: INFO
    handlers: [console]
